# cluster.yaml - cluster configuration for my Snakefile.
__default__:
  time: '2:00:00'

iterative_search:
  time: '5:00:00'

realignment:
  time: '6:00:00'

merged_alignment:
  time: '12:00:00'

phylogeny:
  time: '30:00:00'

merged_taxid_parse:
  time: '8:00:00'

phylogenetic_reconstruction:
  time: '30:00:00'
