# Default threads for processes ran in this pipeline
threads: 20

ram_phylogeny: 30000

# Parent directorry where the analyses will be stored
run: "/groups/doudna/projects/daniel_projects/nomburg_j/ligT_phyrec_cl56"

# Directory that stores input MSA files
input_dir: "/groups/doudna/projects/daniel_projects/nomburg_j/input_dir"

# Email address required for Entrez queries
entrez_login: "thedoudnalab@gmail.com"

# Parent path to the shared database files in the server
shared_db_path: "/shared/db/genbank/257/blast"
#shared_db_path: "/groups/doudna/team_resources/shared_databases/ncbi_nr"

# Prefix name found in the input MSA filename
input_prefix: ["NS1__YP_009058894__Bufavirus-3__1391667", "NS1__YP_009116876__Sesavirus_CSL10538__1519097", "NS1_protein__NP_694863__Human_erythrovirus_V9__72197", "Rep__YP_010086821__Murine_adeno-associated_virus_2__2171378", "non-structural_protein_1__YP_009272913__Mink_bocavirus_1__2259808", "nonstructural_protein_NS1__NP_046813__Diatraea_saccharalis_densovirus__72003", "nonstructural_protein_NS1__YP_009553675__Mouse_kidney_parvovirus__2316143", "nonstructural_protein__YP_009507388__Parvovirus_YX-2010_CHN__754189", "putative_non-structural_protein__YP_009362129__Dysaphis_plantaginea_densovirus__551224"]

cluster: ["56"]

match_colum: "family_taxonID"
add_colum: "family_genome_type"
taxid: "1"


# Name given to the merger of the databases collected for the analysis
db_prefix: ["nr"]

# Path to NCBI taxonomy download directory
taxdump_path: "/groups/doudna/team_resources/shared_databases/taxdump"

# PSI-BLAST custom columns
blast_custom_cols: "qacc sacc evalue pident qcovhsp staxid"

# Jpred internally generated ID -- downloaded from JPRED online server
jpred_id: "jp_T6I_JjO"
