# Default threads for processes ran in this pipeline
threads: 20

ram_phylogeny: 30000

# Parent directorry where the analyses will be stored
run: "/groups/doudna/projects/daniel_projects/nomburg_j/ligT_phyrec_nucleoside_transporter_sequences"

# Directory that stores input MSA files
input_dir: "/groups/doudna/projects/daniel_projects/nomburg_j/input_dir"

# Email address required for Entrez queries
entrez_login: "thedoudnalab@gmail.com"

# Parent path to the shared database files in the server
shared_db_path: "/shared/db/genbank/257/blast"
#shared_db_path: "/groups/doudna/team_resources/shared_databases/ncbi_nr"

# Prefix name found in the input MSA filename
input_prefix: ["F22__YP_009173937__Felis_catus_gammaherpesvirus_1__1452540", "ORF58__NP_065557__Alcelaphine_gammaherpesvirus_1__35252", "Transporter_major_facilitator_subfamily_protein__YP_009165055__Mollivirus_sibericum_Viruses.__X", "UL43__YP_003084378__Anatid_alphaherpesvirus_1__104388", "envelope_protein_UL43__NP_040138__Human_alphaherpesvirus_3__10335", "envelope_protein_UL43__NP_066875__Gallid_alphaherpesvirus_3__35250", "envelope_protein_UL43__YP_009054920__Equid_alphaherpesvirus_3__80341", "envelope_protein_UL43__YP_068346__Suid_alphaherpesvirus_1__10345", "hypothetical_protein_AsGV044__YP_009513074__Agrotis_segetum_granulovirus__10464", "hypothetical_protein_psal_cds_1236__YP_008438639__Pandoravirus_salinus__1349410"]

cluster: ["nucleoside_transporter_sequences"]

match_colum: "family_taxonID"
add_colum: "family_genome_type"
taxid: "1"

# Name given to the merger of the databases collected for the analysis
db_prefix: ["nr"]

# Path to NCBI taxonomy download directory
taxdump_path: "/groups/doudna/team_resources/shared_databases/taxdump"

# PSI-BLAST custom columns
blast_custom_cols: "qacc sacc evalue pident qcovhsp staxid"

# Jpred internally generated ID -- downloaded from JPRED online server
jpred_id: "jp_T6I_JjO"
